-- MySQL Script generated by MySQL Workbench
-- Wed May  8 10:02:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Frame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Frame` (
  `idFrame` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `color` VARCHAR(10) NULL,
  PRIMARY KEY (`idFrame`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provider` (
  `nifProvider` VARCHAR(9) NOT NULL,
  `name` VARCHAR(45) NULL,
  `streetName` VARCHAR(45) NULL,
  `streetNumber` VARCHAR(45) NULL,
  `floor` INT NULL,
  `door` VARCHAR(3) NULL,
  `city` VARCHAR(45) NULL,
  `zipCode` VARCHAR(5) NULL,
  `country` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(10) NULL,
  `faxNumber` VARCHAR(10) NULL,
  PRIMARY KEY (`nifProvider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `idBrand` INT NOT NULL,
  `brandName` VARCHAR(45) NULL,
  `Provider_nifProvider` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idBrand`),
  INDEX `fk_Brand_Provider1_idx` (`Provider_nifProvider` ASC) VISIBLE,
  CONSTRAINT `fk_Brand_Provider1`
    FOREIGN KEY (`Provider_nifProvider`)
    REFERENCES `mydb`.`Provider` (`nifProvider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Worker` (
  `idWorker` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idWorker`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `idCustomer` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `streetName` VARCHAR(45) NULL,
  `streetNumber` VARCHAR(45) NULL,
  `floor` INT NULL,
  `door` VARCHAR(3) NULL,
  `city` VARCHAR(45) NULL,
  `zipCode` VARCHAR(5) NULL,
  `country` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(10) NULL,
  `mail` VARCHAR(45) NULL,
  `registreDate` DATETIME NULL,
  `RecomendBy_Customer_idCustomer` INT NULL,
  PRIMARY KEY (`idCustomer`),
  INDEX `fk_Customer_Customer1_idx` (`RecomendBy_Customer_idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Customer1`
    FOREIGN KEY (`RecomendBy_Customer_idCustomer`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sale` (
  `idSale` INT NOT NULL,
  `date` DATETIME NULL,
  `Worker_idWorker` INT NOT NULL,
  `Customer_idCustomer` INT NOT NULL,
  PRIMARY KEY (`idSale`),
  INDEX `fk_Sale_Worker1_idx` (`Worker_idWorker` ASC) VISIBLE,
  INDEX `fk_Sale_Customer1_idx` (`Customer_idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_Sale_Worker1`
    FOREIGN KEY (`Worker_idWorker`)
    REFERENCES `mydb`.`Worker` (`idWorker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sale_Customer1`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Glasses` (
  `idGlasses` INT NOT NULL,
  `price` DECIMAL(2) NULL,
  `Frame_idFrame` INT NOT NULL,
  `Brand_idBrand` INT NOT NULL,
  `Sale_idSale` INT NOT NULL,
  PRIMARY KEY (`idGlasses`),
  INDEX `fk_Glasses_Frame_idx` (`Frame_idFrame` ASC) VISIBLE,
  INDEX `fk_Glasses_Brand1_idx` (`Brand_idBrand` ASC) VISIBLE,
  INDEX `fk_Glasses_Sale1_idx` (`Sale_idSale` ASC) VISIBLE,
  CONSTRAINT `fk_Glasses_Frame`
    FOREIGN KEY (`Frame_idFrame`)
    REFERENCES `mydb`.`Frame` (`idFrame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glasses_Brand1`
    FOREIGN KEY (`Brand_idBrand`)
    REFERENCES `mydb`.`Brand` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glasses_Sale1`
    FOREIGN KEY (`Sale_idSale`)
    REFERENCES `mydb`.`Sale` (`idSale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Glass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Glass` (
  `idGlass` INT NOT NULL,
  `color` VARCHAR(45) NULL,
  `graduation` VARCHAR(45) NULL,
  `Glasses_idGlasses` INT NOT NULL,
  PRIMARY KEY (`idGlass`),
  INDEX `fk_Glass_Glasses1_idx` (`Glasses_idGlasses` ASC) VISIBLE,
  CONSTRAINT `fk_Glass_Glasses1`
    FOREIGN KEY (`Glasses_idGlasses`)
    REFERENCES `mydb`.`Glasses` (`idGlasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Frame`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Frame` (`idFrame`, `type`, `color`) VALUES (1, 'FLOTANT', 'vermell');
INSERT INTO `mydb`.`Frame` (`idFrame`, `type`, `color`) VALUES (2, 'PASTA', 'blau');
INSERT INTO `mydb`.`Frame` (`idFrame`, `type`, `color`) VALUES (3, 'METAL·LICA', 'negre');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Provider`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Provider` (`nifProvider`, `name`, `streetName`, `streetNumber`, `floor`, `door`, `city`, `zipCode`, `country`, `phoneNumber`, `faxNumber`) VALUES ('1234', 'ullSol', 'glories', '34', 44, '2', 'Barcelona', '08013', 'Spain', '9333333333', '934444444');
INSERT INTO `mydb`.`Provider` (`nifProvider`, `name`, `streetName`, `streetNumber`, `floor`, `door`, `city`, `zipCode`, `country`, `phoneNumber`, `faxNumber`) VALUES ('4444b', 'NOveig', 'ciber', '77b', 1, '1', 'Sabadell', '09892', NULL, '9123445646', '9743782722');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Brand`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Brand` (`idBrand`, `brandName`, `Provider_nifProvider`) VALUES (1, 'FFF', '1234');
INSERT INTO `mydb`.`Brand` (`idBrand`, `brandName`, `Provider_nifProvider`) VALUES (2, 'BBBB', '4444b');
INSERT INTO `mydb`.`Brand` (`idBrand`, `brandName`, `Provider_nifProvider`) VALUES (3, 'CCCC', '4444b');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Worker`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Worker` (`idWorker`, `name`) VALUES (1, 'OHDIUH');
INSERT INTO `mydb`.`Worker` (`idWorker`, `name`) VALUES (2, 'DHHOIUPD');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Customer` (`idCustomer`, `name`, `streetName`, `streetNumber`, `floor`, `door`, `city`, `zipCode`, `country`, `phoneNumber`, `mail`, `registreDate`, `RecomendBy_Customer_idCustomer`) VALUES (1, 'Pepito Client', 'Fontanella', '3', 5, '5', 'Paris', 'i37y37', 'França', '94767488477', 'hdhjajjs@hfjfj.es', '24/04/2019', 3);
INSERT INTO `mydb`.`Customer` (`idCustomer`, `name`, `streetName`, `streetNumber`, `floor`, `door`, `city`, `zipCode`, `country`, `phoneNumber`, `mail`, `registreDate`, `RecomendBy_Customer_idCustomer`) VALUES (2, 'Leli f', 'Pujades', '56', 7, 'a', 'Nice', 'u73637', 'França', '93737847478', NULL, '30/04/2019', 777);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Sale`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Sale` (`idSale`, `date`, `Worker_idWorker`, `Customer_idCustomer`) VALUES (1, '25/04/2019', 1, 1);
INSERT INTO `mydb`.`Sale` (`idSale`, `date`, `Worker_idWorker`, `Customer_idCustomer`) VALUES (2, '26/04/2019', 2, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Glasses`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Glasses` (`idGlasses`, `price`, `Frame_idFrame`, `Brand_idBrand`, `Sale_idSale`) VALUES (1, 120.25, 1, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Glass`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Glass` (`idGlass`, `color`, `graduation`, `Glasses_idGlasses`) VALUES (1, 'FOSC', '1', 1);
INSERT INTO `mydb`.`Glass` (`idGlass`, `color`, `graduation`, `Glasses_idGlasses`) VALUES (2, 'FOSC', '1.25', 1);
INSERT INTO `mydb`.`Glass` (`idGlass`, `color`, `graduation`, `Glasses_idGlasses`) VALUES (3, 'CLAR', '2.1', 2);
INSERT INTO `mydb`.`Glass` (`idGlass`, `color`, `graduation`, `Glasses_idGlasses`) VALUES (4, 'CLAR', '1.6', 2);

COMMIT;

